### ISSUE TITLE
Positions has been removed

### ISSUE THREAD

**Issue by elliotwhitehead** [HackCU/Startups2Students#31]
Slightly urgent: 

![image](https://user-images.githubusercontent.com/3988879/37800995-7a1b53e2-2dea-11e8-9d1a-58a21a02ceda.png)

It seems that the positions category has been removed, but the link at the top of the page is there. 

Do we plan on adding that back in? I think it was really nice to give students an idea of who should come (not just web dev etc.). 

Either way, we should remove the positions menu item if there is no positions section.

**Comment by casassg** [comment]
Closing this
